/*
 * File: app/view/BoardGamesAdmin.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaCrud.view.BoardGamesAdmin', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.boardgamesadmin',

    requires: [
        'SenchaCrud.view.BoardGamesAdminViewModel',
        'Ext.Container'
    ],

    viewModel: {
        type: 'boardgamesadmin'
    },

    items: [
        {
            xtype: 'container',
            title: 'Tab 1'
        },
        {
            xtype: 'container',
            title: 'Tab 2'
        },
        {
            xtype: 'container',
            title: 'Tab 3'
        }
    ]

});