/*
 * File: app/view/BoardGamesAdmin.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaCrud.view.BoardGamesAdmin', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.boardgamesadmin',

    requires: [
        'SenchaCrud.view.BoardGamesAdminViewModel',
        'SenchaCrud.view.BoardGamesAdminViewController',
        'Ext.grid.Grid',
        'Ext.grid.column.Column',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    controller: 'boardgamesadmin',
    viewModel: {
        type: 'boardgamesadmin'
    },

    items: [
        {
            xtype: 'container',
            title: 'Tab 1'
        },
        {
            xtype: 'container',
            title: 'People',
            items: [
                {
                    xtype: 'grid',
                    height: '100%',
                    width: '100%',
                    store: 'People',
                    columns: [
                        {
                            xtype: 'column',
                            flex: '1',
                            width: 70,
                            dataIndex: 'firstName',
                            text: 'First Name'
                        },
                        {
                            xtype: 'column',
                            flex: '1',
                            width: 70,
                            dataIndex: 'lastName',
                            text: 'Last Name'
                        }
                    ],
                    listeners: {
                        itemsingletap: 'onPersonGridItemSingleTap'
                    }
                },
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'New Person',
                            listeners: {
                                tap: 'onNewPersonButtonTap'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            title: 'Statuses',
            items: [
                {
                    xtype: 'grid',
                    height: '100%',
                    itemId: 'statusgrid',
                    width: '100%',
                    store: 'Statuses',
                    columns: [
                        {
                            xtype: 'column',
                            flex: '1',
                            width: 70,
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'column',
                            flex: '2',
                            width: 70,
                            dataIndex: 'description',
                            text: 'Description'
                        }
                    ],
                    listeners: {
                        itemsingletap: 'onStatusGridItemSingleTap'
                    }
                },
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'newstatusbutton',
                            text: 'New Status',
                            listeners: {
                                tap: 'onNewStatusButtonTap'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});