/*
 * File: app/model/Status.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaCrud.model.Status', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],


    fields: [
        {
            name: 'name'
        },
        {
            name: 'description'
        }
    ],
    proxy: {
        type: 'rest',
        url: 'http://localhost:8080/api/statuses',
        reader: {
            type: 'json',
            rootProperty: '_embedded.statuses'
        }
    }

});